### ISSUE TITLE
I can't build

### ISSUE THREAD

**Issue by 5NORLAX** [luis605/Lit-Engine-OLD#34]
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/MinGW/bin/gcc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/MinGW/bin/c++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Python3: Programs/Python/Python312/libs/python312.lib (found version "3.12.3") found components: Development Development.Module Development.Embed
WIN32 Called
-- Configuring done (3.7s)
CMake Error at CMakeLists.txt:88 (add_executable):
  Cannot find source file:

    ImGuiColorTextEdit/TextEditor.o

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm
  .ccm .cxxm .c++m .h .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90
  .f95 .f03 .hip .ispc

CMake Error at CMakeLists.txt:88 (add_executable):
  No SOURCES given to target: lit_engine

CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by luis605** [comment]
There's an issue with the Windows build system. It seems that the CMakeLists.txt wasn't properly updated to align with the recent structural redesign. I'll address this promptly.

**Comment by luis605** [comment]
@5NORLAX The issue is almost fixed, I'm just solving some linker errors and it should all be good to go.

**Comment by 5NORLAX** [comment]
can you make commit?

**Comment by luis605** [comment]
> can you make commit?

I'm just solving some linker errors and it should all be good to go. I will send a commit after the issue is completely fixed and tested.

**Comment by luis605** [comment]
@5NORLAX I just committed my changes, can you check them out?

**Comment by 5NORLAX** [comment]
you know that you can make commit for issue not for full project? also you can create new branch like dev or something

**Comment by luis605** [comment]
@5NORLAX The Windows build system underwent an overhaul to address the mentioned issues. You should be able to compile the engine using the new system. Thank you for reporting this incident.
