### ISSUE TITLE
I'm having difficulty compiling to Windows

### ISSUE THREAD

**Issue by WOLFxxxxxx** [luis605/Lit-Engine-OLD#39]
****

**Comment by luis605** [comment]
What seems to be your issue? Is it an error or is it something else?

**Comment by WOLFxxxxxx** [comment]
![a1](https://github.com/user-attachments/assets/e388d8d8-a8cf-41c5-8d48-52de3f81aa88)
![a2](https://github.com/user-attachments/assets/ecffc9c9-1b16-4ef1-b8d8-fe566cb2e788)

![a3](https://github.com/user-attachments/assets/dc90785b-e962-4fa6-836f-d9b023f7c9be)

**Comment by luis605** [comment]
I believe I see the problem. Instead of compiling with MSVC, you should use MinGW makefiles instead use `cmake .. -G "MinGW Makefiles" --fresh`. Inside the ReadME, there are the correct installation and building commands you can follow. If you have any other problems, feel free to reply here.

**Comment by WOLFxxxxxx** [comment]
![a1](https://github.com/user-attachments/assets/81fdb257-be53-43b8-aec9-a7da0af58f88)
![a2](https://github.com/user-attachments/assets/3b5df510-2d79-42e6-ac6a-4efcdbe81305)

**Comment by WOLFxxxxxx** [comment]
![a4](https://github.com/user-attachments/assets/3aeaeb83-6fce-4674-a12b-60ae47a346ea)

**Comment by luis605** [comment]
GCC seems to be more permissive when casting types. Since I'm primarily using Linux, I don't run into those issues with frequency. I will update the type casting soon and you should be able to build and run the engine.

**Comment by WOLFxxxxxx** [comment]
Thanks ♥️

**Comment by luis605** [comment]
I have push a new commit with the compilation fixes. It should solve the compilation errors.

**Comment by luis605** [comment]
Closing issue as completed.
