### ISSUE TITLE
If the scene contains an entity and you press play, the engine crashes.

### ISSUE THREAD

**Issue by WOLFxxxxxx** [luis605/Lit-Engine-OLD#42]
The engine works when I press play, but if the scene contains an entity and I press play, the engine crashes.

Problem message
libc++sdi trminating due to nucaught excption of type std::length_error: vector
![a1](https://github.com/user-attachments/assets/61a20b7f-b4d4-4d0c-92d3-8920782f9ccc)

**Comment by luis605** [comment]
There was an incorrect vector assignment in SceneEditor which has been fixed. Thank you for reporting.
