### ISSUE TITLE
When you press play, the images turn black.

### ISSUE THREAD

**Issue by WOLFxxxxxx** [luis605/Lit-Engine-OLD#46]
![a1](https://github.com/user-attachments/assets/7ed4b639-bef2-46d0-9406-fcdf7e1e88ee)

![a2](https://github.com/user-attachments/assets/5b0d44b5-6493-4e83-aae2-89f456992c85)

**Comment by luis605** [comment]
The issue when assigning entitiesListPregame to entitiesList. The copy constructor would be called which would call surface material's clean up function inside the copy constructor. I commented out the code because it may need to be re-added with a special condition to prevent issues like these.

**Comment by luis605** [comment]
Closing as solved-
